### PR TITLE
Add Cyberpunk Neon theme for Telegram Android

### PR DESCRIPTION
**Pull request by nitanmarcel**
Ported to Android using @ThemesPorterBot and optimized by me. 

IMG_20201104_113837_676

### CODE REVIEW

**Comment by nitanmarcel** [comment]
You can test it by pressing this link:

https://t.me/addtheme/N7rYB60wL13Y9F7g

**Comment by nitanmarcel** [comment]
I was kinda fast to push this theme, it still needs a good wallpaper and I've found a few things that needs to be changed

**Comment by Roboron3042** [comment]
Thank you for this, it is very appreciated. Just let me know when it is ready.

**Comment by nitanmarcel** [comment]
@Roboron3042 Sorry for the mess xD.

The theme it's done now, done some fixes and upscaled the background image, I couldn't find a good replacement for it but it doesn't look as bad.

You can try it here: https://t.me/addtheme/d6RZgRjZKG8xGisW

image

**Comment by nitanmarcel** [comment]
Fixed a small thing in bots with the keyboard that appears under the input bar on some bots

**Comment by Roboron3042** [comment]
Fantastic. Finally we have both Telegram themes. Thank you!

**Comment by nitanmarcel** [comment]
> Fantastic. Finally we have both Telegram themes. Thank you!

No problem. If I find more bugs or if someone else opens other issues I'll make a PR

**Comment by nitanmarcel** [comment]
Actually, I'll push a update tonight with some fixes and a link in the readme that if the theme is applied with that it will auto-update when I fix something

**Pull request merged**
