### PR TITLE
Add colors patch for st

### PR DESCRIPTION
**Pull request by cybvik**

### CODE REVIEW

**Comment by cybvik** [comment]
Sorry for the inconvenience. I mistakenly thought I messed up the patch, but it is alright.

**Comment by Roboron3042** [comment]
Thank you for your contribution! I am not sure a .diff file is the best thing, as this assumes (I guess) that the config is the default, but in reality an user may have tweaked its config file earlier (and if such user came here, they like to customize, so they probably did).

**Comment by cybvik** [comment]
That is right, the .diff will only work with the default configs. I did this because on st.suckless.org/patches all the patches are available as .diff as well. But I can change this to a regular file, so users don't get confused and maybe open issues.

**Comment by Roboron3042** [comment]
Thank you :-)

**Pull request merged**
